config/routes.rb
Rails.application.routes.draw do
   get    'signup'  => 'users#new'
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'

   resources :results
   resources :simple_results,  controller: 'results', type: 'SimpleResult' 
   resources :survey_results,  controller: 'results', type: 'SurveyResult'

   resources :tasks
   resources :simple_tasks,  controller: 'tasks', type: 'SimpleTask' 
   resources :survey_tasks,  controller: 'tasks', type: 'SurveyTask'
   resources :meeting_tasks, controller: 'tasks', type: 'MeetingTask' 
   resources :social_tasks,  controller: 'tasks', type: 'SocialTask'

   
  
   resources :users
   get 'users/:id/tasks' => 'tasks#my_tasks'
   resources :surveys

  apipie
   get 'home/index'

 

  root 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :survey_result
  has_and_belongs_to_many :options
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  self.inheritance_column = :type
  scope :simples, -> { where(type: 'SimpleResult') } 
  scope :surveys, -> { where(type: 'SurveyResult') } 
 
  
  def self.types
     %w(SimpleResult SurveyResult)
  end
end

class SurveyResult < Result
  belongs_to :survey 
  has_many :answers
  accepts_nested_attributes_for :answers, :allow_destroy => true
  def self.model_name
    Result.model_name
  end
end

class SimpleResult < Result
  def self.model_name
    Result.model_name
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  before_action :get_relations, only:[:new, :edit]
  # GET /results
  # GET /results.json
  def index
       @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @survey = Survey.find(@result.survey_id)
  end

  # GET /results/new
  def new
    if params[:type] == :SurveyResult
      @result = Result::SurveyResult.new
      @survey = Survey.find(params[:survey_id])
      @survey.questions.each do |question|
         @result.answers.build(question_id:question.id)
      end
    else
      @result = Result.new 
    end

  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end
    
    def get_relations
      @users = User.all
      @tasks = Task.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:task_id, :user_id, 
                                     :started_date, 
                                     :ended_date, :comment, 
                                     :survey_id,
                                     :type, answers_attributes:[:content, :question_id, {:option_ids=>[]}])
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_answer_fields.erb
 <%
  	question_id = f.object.attributes["question_id"] 
  	question = Question.find(question_id) 
  %>
<p>
  <h4><%= question.content%></h4>
  <%= f.hidden_field :question_id, :value=>question_id%>
  <%if question.options %>
  	  <%= f.collection_check_boxes :option_ids, question.options, :id, :content %>
  <%else%>
	  <%= f.label :content, "Answer" %><br />
	  <%= f.text_area :content, :rows => 3 %><br />
  <%end%>
</p>
<hr/>

app/views/results/_form.html.erb
<%= form_for (@result)  do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :started_date %><br>
    <%= f.datetime_select :started_date %>
  </div>
  <div class="field">
    <%= f.label :ended_date %><br>
    <%= f.datetime_select :ended_date %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
   <div class="field">
    <%= f.label :type %><br>
    <%=  f.select :type, Result.types {|type| [type.titleize,type]}, :selected => params[:type]  %><br>
  </div>
  <div class="field">
    <%= f.label :task_id, "Tareas" %><br>
    <%= f.select :task_id, @tasks.map{ |u| [u.name, u.id] }, :selected => :task_id %><br>
  </div>
  <div class="field">
    <%= f.label :user_id, "Usuario" %><br>
    <%= f.select :user_id, @users.map{ |u| [u.name, u.id] }, :selected => :user_id %><br>
  </div>
  <% case params[:type]  %>  
      <% when "SurveyResult" %>
      	<div id="survey">
      		<div class="field">
			    <%= f.label :survey_id, "Survey" %><br>
			    <input type="text" value="<%=@survey.name%>" readonly="readonly"/><br>
			    <%=f.hidden_field :survey_id, :value=>@survey.id%>
			</div>
			 <div class="answers">
					<%= f.fields_for :answers do |answer_builder| %>
				    	<%= render "answer_fields", :f => answer_builder %>
				  	<% end %>
			  </div>
      	</div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>Started date</th>
      <th>Ended date</th>
      <th>Comment</th>
      <th>Task</th>
      <th>User</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.started_date %></td>
        <td><%= result.ended_date %></td>
        <td><%= result.comment %></td>
        <td><%= result.task.name %></td>
        <td><%= result.user.name %></td>
         <td><%= result.type %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Completed task', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Task:</strong>
  <%= @result.task.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @result.user.name %>
</p>

<p>
  <strong>Started date:</strong>
  <%= @result.started_date %>
</p>

<p>
  <strong>Ended date:</strong>
  <%= @result.ended_date %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @result.comment %>
</p>

<p>
  <strong>Type:</strong>
  <%= @result.type %>
</p>
<% if @result.type == "SurveyResult"%>
	<div class="survey">
		<p>
			<strong>Survey:</strong>
			<%=@survey.name%>
		</p>
		<p>
			<ul>
				<%@result.answers.each do |answer|%>
					<li>
						<strong><%=answer.question.content%></strong><br/>
						<%if answer.content %>
							<%=asnwer.content%>
						<%else%>
							<%answer.options.each do |option|%>
								<%=option.content%><br/>
							<%end-%>
						<%end-%>
					</li>
				<%end-%>
			</ul>
		</p>
	</div>
<%end-%>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>