config/routes.rb
Rails.application.routes.draw do
   get    'signup'  => 'users#new'
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'

   resources :results
   resources :simple_results,  controller: 'results', type: 'SimpleResult' 
   resources :survey_results,  controller: 'results', type: 'SurveyResult'

   resources :tasks
   resources :simple_tasks,  controller: 'tasks', type: 'SimpleTask' 
   resources :survey_tasks,  controller: 'tasks', type: 'SurveyTask'
   resources :meeting_tasks, controller: 'tasks', type: 'MeetingTask' 
   resources :social_tasks,  controller: 'tasks', type: 'SocialTask'

   
  
   resources :users
   get 'users/:id/tasks' => 'tasks#my_tasks'
   resources :surveys

  apipie
   get 'home/index'

 

  root 'home#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  3.times { 
      questions = @survey.questions.build
      3.times{
          options = questions.options.build
        }
     }
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    
    respond_to do |format|
      if @survey.save    
        @preguntas = @survey.questions
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.includes(questions: :options).find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description,  
                                     questions_attributes: [:content, :survey_id,
                                        :is_required, :id,:max_options, :min_options,
                                     options_attributes:[:question_id,:content, :id]])
    end
   
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for @survey  do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <hr/>
  <h3>Preguntas</h3>
  <div class="questions">
	 <%= f.fields_for :questions do |question_builder| %>
    	<%= render "question_fields", :f => question_builder %>
  	 <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_option_fields.erb
<p>
  <%= f.label :content, "Option" %><br />
  <%= f.text_field :content %><br />
</p>

app/views/surveys/_question_fields.erb
<p>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content, :rows => 3 %><br />
  <%=  f.select(:type, Question.types.keys.map {|type| [type.titleize,type]})  %><br>
  <%= f.check_box :is_required %> obligatoria<br/>
  <%= f.label :min_options, "Minimo de respuestas" %><br />
  <%= f.number_field :min_options %> <br>
  <%= f.label :max_options, "Maximo de respuestas" %><br />
  <%= f.number_field :max_options %> <br>
  <%= f.fields_for :options do |option_builder| %>
    <%= render "option_fields", :f => option_builder %>
  <% end %>
</p>
<hr/>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.name %></td>
        <td><%= survey.description %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survey.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>
<p>
	<ol>
		<% @survey.questions.each  do |question|%>
			 <li>
			 	<span style="font-weight:<%="bold" if question.is_required %>">
			 		<%= question.content %>
			 	</span><br>
			 	max: <%= question.max_options%><br>
			 	min: <%= question.min_options%><br>
			 	<br/>
			 	opciones:
			 	<br/>
			 	<ul type="square">
			 		<% question.options.each do |option|%>
			 		<li><%=option.content%></li>
			 		<%end%>
			 	</ul>
			 </li> 
		<%end%>
	</ol>
</p>
<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>